[package]
name = "eventsource-client"
version = "0.1.0"
authors = ["Sam Stokes <sstokes@launchdarkly.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
log = "0.4.6"
reqwest = "0.9.11"

[dev-dependencies]
maplit = "1.0.1"
simplelog = "0.5.3"
