version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - run: cargo check
      - run: cargo build
      - run: cargo test
      - run: cargo doc --no-deps

      - store_artifacts:
          path: target/doc
          destination: doc
